use testlms;
CREATE TABLE  E_BOOK (
   	CALLNO VARCHAR(50), 
	NAME VARCHAR(50), 
	AUTHOR VARCHAR(50), 
	PUBLISHER VARCHAR(50), 
	QUANTITY int, 
	ISSUED int, 
	 CONSTRAINT E_BOOK_PK PRIMARY KEY (CALLNO)
   );
CREATE TABLE  E_LIBRARIAN
   (	ID int, 
	NAME VARCHAR(50), 
	PASSWORD VARCHAR(50), 
	EMAIL VARCHAR(50), 
	MOBILE int, 
	 CONSTRAINT E_LIBRARIAN_PK PRIMARY KEY (ID)
   );


CREATE TABLE  E_ISSUEBOOK 
   (	CALLNO VARCHAR(50) NOT NULL, 
	STUDENTID VARCHAR(50) NOT NULL, 
	STUDENTNAME VARCHAR(50), 
	STUDENTMOBILE int, 
	ISSUEDDATE DATE, 
	RETURNSTATUS VARCHAR(50)
   )



